baseurl = "https://sarusworld.github.io/"  
title = "Sarus World"

languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"


[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1



[[menu.main]]
    name       = "Services"
    identifier = "menu.features"
    url        = "/services/"
    weight     = 3



# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/SarusMarket/miniature-goggles"
    pre = "<i class='bi bi-github'></i>"



[params]
    about_us = "<p>IT Services</p>"
    copyright = "SarusWorld; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"
    logo_text = "Sarus World"
    logo = "img/logo.jpg"
    logo_small = "img/logo-small.jpg"
    contact_url = "/contact"
    address = """<p class="text-uppercase">
    <strong>Sarus IT Services</strong>
    <br>Bengaluru, <strong>India</strong></p>
      """


# Enable or disable top bar with social icons
[params.topbar]
    text = """<p class="hidden-sm hidden-xs"><strong>Welcome to Sarus World</strong>  <i class="bi bi-envelope-fill"></i></a>.</p>"""

[params.services]
    cols = 3 # Default: 3, Available values 2,3,4,6
    
